name: Publish
on:
  push:
    tags:
      - "v0.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: my-test-environment
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
    # get tag variable using {{ github.ref_name }}
    #
    # References:
    # * https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    # * https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
    - name: extract gem version from tag
      id: vars
      run: echo version=${{ github.ref_name }} | sed -e 's/v0/0/' >> $GITHUB_OUTPUT
    #
    # From gem push documents.
    #
    # The push command will use ~/.gem/credentials to authenticate to a server,
    # but you can use the RubyGems environment variable GEM_HOST_API_KEY
    # to set the api key to authenticate.
    #
    # https://guides.rubygems.org/command-reference/#gem-push
    #
    - name: echo test
      run: |
        echo ${HOGEHOGE}
      env:
        HOGEHOGE: ${{secrets.HOGEHOGE}}
    - name: Publish
      run: |
        rake build
        ls pkg/*
        gem push pkg/${EMBULK_PLUGIN_NAME}-${{ steps.vars.outputs.version }}.gem
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        gem push pkg/embulk-output-bigquery-${{ steps.vars.outputs.version }}.gem
      env:
        EMBULK_PLUGIN_NAME: embulk-input-hiroysato
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
