name: Publish
on:
  push:
    tags:
      - "v0.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
    - name: extract gem version from tag
      id: vars
      run: echo version=v0.1.0 | sed -e 's/v0/0/' >> $GITHUB_OUTPUT
    - name: echo version
      run: echo "release ${{ steps.vars.outputs.version }}"
    - name: build gem
      run: |
        rake build
    - name: test ls
      run: |
        ls pkg/*
    - name: Publish
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem push pkg/embulk-output-bigquery-${{ steps.vars.outputs.version }}.gem
      env:
        RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
